#!/usr/bin/env bash
# ---------------------------------------------------------------------------- #
#        Apache 2.0 License Copyright © 2022-2023 The Aurae Authors            #
#                                                                              #
#                +--------------------------------------------+                #
#                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |                #
#                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |                #
#                |  ███████║██║   ██║██████╔╝███████║█████╗   |                #
#                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |                #
#                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |                #
#                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |                #
#                +--------------------------------------------+                #
#                                                                              #
#                         Distributed Systems Runtime                          #
#                                                                              #
# ---------------------------------------------------------------------------- #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
# ---------------------------------------------------------------------------- #

# validate pki

line_break() {
  echo '-----------------------------------------------------------------------'
}

# determines if a container is running
is_container_not_running() {
    [[ "$(docker inspect -f '{{.State.Running}}' "$1" 2>/dev/null)" == "false" ]]
}

container_name='aurae-dev'

# start, run, and exec as appropriate to maximize container reuse
if docker ps -a --format '{{.Names}}' | grep -q "^${container_name}$"; then
  echo "executing command in the existing dev container"

  if is_container_not_running "$container_name" ; then
    echo "$container_name was stopped, restarting..."
    if [ $# -eq 0 ] ; then
      echo 'starting container with interactive shell...'
      line_break
      docker start -ai "${container_name}"
      exit 0
    else
      echo 'starting container...'
      line_break
      docker start "${container_name}"
      docker exec -it "${container_name}" "$@"
      exit 0
    fi
  else
    # container is running, simply run command
    if [ $# -eq 0 ] ; then
      echo 'starting interactive shell...'
      docker exec -it "${container_name}" /bin/bash
    else
      echo "command: $@"
      docker exec -it "${container_name}" "$@"
    fi
  fi
else
  echo "starting new dev container $container_name"
  line_break
  docker run -it \
    --name "$container_name" \
    -v ~/.config/nvim:/root/.config/nvim/ \
    -v /etc/aurae:/etc/aurae \
    -v .:/aurae \
    aurae/dev:latest "$@"
fi
